secret_key = 'secret-key'
POSTGRES_USER = 'online-sofa-project'
POSTGRES_PASSWORD = 'online-sofa-project'
email_host = 'email-host'
email_port = 0
email_host_user = 'email-host-user'
email_host_password = 'email-host-password'
recaptcha_google_key_site = ['-', '-']
STRIPE_APIKEY = 'stripe-apikey'