# Generated by Django 3.1.3 on 2020-11-14 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_app', '0003_registrationconfirmationbyemail_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationconfirmationbyemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registrationconfirmationbyemail',
            name='username',
        ),
        migrations.AddField(
            model_name='registrationconfirmationbyemail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
