# Generated by Django 3.1.3 on 2020-11-04 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_auto_20201104_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название рубрики'),
        ),
    ]
