# Generated by Django 3.1.3 on 2020-11-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20201104_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения товара'),
        ),
    ]
