# Generated by Django 3.1.3 on 2020-11-12 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Изображения товара'),
        ),
    ]
