# Generated by Django 3.1.3 on 2020-11-15 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_auto_20201115_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/store_app/products/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Изображения товара'),
        ),
    ]
