# Generated by Django 3.1.3 on 2020-12-01 06:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0012_auto_20201125_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_products', models.SmallIntegerField(validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Количество товаров')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Ячейка для хранения одной позиции товара',
                'verbose_name_plural': 'Склад товаров',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Basket_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product', verbose_name='Товары в корзине')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корзина пользователя')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Корзина пользователя с товарами',
                'ordering': ['products'],
            },
        ),
    ]
