# Generated by Django 3.1.3 on 2020-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_basket_user_warehouse_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_products',
            name='count_products',
            field=models.PositiveSmallIntegerField(verbose_name='Количество товаров'),
        ),
    ]
