# Generated by Django 3.1.3 on 2020-12-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_auto_20201201_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-sale_start_time'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
