# Generated by Django 3.1.3 on 2020-12-06 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0016_auto_20201202_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketUser',
            new_name='CartUser',
        ),
    ]
