# Generated by Django 3.1.3 on 2020-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_countproductsincart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountProductsInCart',
            new_name='CountProductInCart',
        ),
        migrations.RenameField(
            model_name='countproductincart',
            old_name='count_products_in_basket',
            new_name='count_product_in_cart',
        ),
    ]
