# Generated by Django 3.1.3 on 2020-12-12 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_auto_20201207_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_comment',
            new_name='date_comment',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер заказа')),
                ('date_order', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заказа')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Электронная почта покупателя')),
                ('name_recipient', models.CharField(max_length=50, verbose_name='Имя получателя заказа')),
                ('surname_recipient', models.CharField(max_length=50, verbose_name='Фамилия получателя заказа')),
                ('phone_recipient', models.CharField(max_length=14, verbose_name='Номер телефона получателя заказа')),
                ('payment_method', models.CharField(max_length=30, verbose_name='Способ оплаты')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Итоговая цена заказа')),
                ('cart_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.cartuser', verbose_name='Корзина покупателя')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['cart_products', 'date_order'],
            },
        ),
    ]
