# Generated by Django 3.1.3 on 2020-12-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_auto_20201212_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.cartuser', verbose_name='Корзина покупателя'),
        ),
    ]
