# Generated by Django 3.1.3 on 2021-01-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0022_auto_20201212_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipient', models.CharField(max_length=50, verbose_name='Имя получателя заказа')),
                ('surname_recipient', models.CharField(max_length=50, verbose_name='Фамилия получателя заказа')),
                ('phone_recipient', models.CharField(max_length=14, verbose_name='Номер телефона получателя заказа')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_recipient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_recipient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surname_recipient',
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store_app.recipient', verbose_name='Получатель'),
            preserve_default=False,
        ),
    ]
