# Generated by Django 3.1.3 on 2021-01-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_auto_20210113_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_order', 'num_order', 'buyer_email'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_products',
        ),
        migrations.AddField(
            model_name='order',
            name='method_receive_order',
            field=models.CharField(default='Самовывоз', max_length=30, verbose_name='Способ оплаты'),
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product_in_order', models.PositiveIntegerField(verbose_name='Количество данного товара')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product', verbose_name='Название товара')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
                'ordering': ['product', 'count_product_in_order'],
            },
        ),
    ]
