# Generated by Django 3.1.3 on 2021-01-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_auto_20210116_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата получения заказа'),
        ),
    ]
