# Generated by Django 3.1.3 on 2021-01-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0026_auto_20210116_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsinorder',
            old_name='Order',
            new_name='order',
        ),
    ]
