# Generated by Django 3.1.3 on 2021-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0027_auto_20210116_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['name_recipient', 'surname_recipient'], 'verbose_name': 'Получатель заказа', 'verbose_name_plural': 'Получатели заказа'},
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name_recipient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя получателя заказа'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone_recipient',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер телефона получателя заказа'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='surname_recipient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия получателя заказа'),
        ),
    ]
