# Generated by Django 3.1.3 on 2021-01-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0028_auto_20210116_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.order', verbose_name='Заказ'),
        ),
    ]
