# Generated by Django 3.1.3 on 2021-01-19 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_auto_20210118_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackWithClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Имя клиента')),
                ('phone_client', models.CharField(max_length=14, verbose_name='Номер телефона для обратной связи')),
                ('email_client', models.EmailField(max_length=254, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Электронная почта для обратной связи')),
                ('given_feedback', models.BooleanField(default=False, verbose_name='Дана ли обратная связь?')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
                'ordering': ['name_client', 'phone_client', 'email_client', 'given_feedback'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='method_receive_order',
            field=models.CharField(default='Самовывоз', max_length=30, verbose_name='Способ получения заказа'),
        ),
    ]
