# Generated by Django 3.1.3 on 2021-01-20 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0030_auto_20210119_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackwithclient',
            name='question_client',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Вопрос клиента'),
        ),
    ]
