# Generated by Django 3.1.3 on 2021-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0032_product_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Число отзывов на товар'),
        ),
    ]
