# Generated by Django 3.1.3 on 2021-02-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0033_product_count_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackwithclient',
            name='phone_client',
            field=models.CharField(max_length=15, verbose_name='Номер телефона для обратной связи'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone_recipient',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона получателя заказа'),
        ),
    ]
